spring.application.name=gestioneordinirestclient
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
server.servlet.context-path=/api

payment.service.url=${PAYMENT_SERVICE}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate; update / create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${MQ_USER}
spring.rabbitmq.password=${MQ_PASS}